package admin

import("context";"reflect";"testing";"time")

type importFake struct{clients []ClientUpsert;saved []ClientRef;pending []PendingInvoice;upserted,inserted []InvoiceWrite}
func(f *importFake)UpsertClients(_ context.Context,v []ClientUpsert)([]ClientRef,error){f.clients=v;return f.saved,nil};func(f *importFake)PendingInvoices(context.Context,[]string,[]string)([]PendingInvoice,error){return f.pending,nil};func(f *importFake)UpsertInvoices(_ context.Context,v []InvoiceWrite)(int,error){f.upserted=v;return len(v),nil};func(f *importFake)InsertInvoices(_ context.Context,v []InvoiceWrite)(int,error){f.inserted=v;return len(v),nil}
func pointer[T any](v T)*T{return &v}
func TestImportPreservesCurrentBatchSemantics(t *testing.T){f:=&importFake{saved:[]ClientRef{{ID:"c1",Phone:"11999999999"},{ID:"c2",Phone:"2188888888"}},pending:[]PendingInvoice{{ID:"old",ClientID:"c1",DueDate:"2026-10-10"}}};got,err:=NewImporter(f).Import(context.Background(),ImportInput{DueDate:"2026-09-30",Rows:[]ImportRow{{Phone:"+55 (11) 99999-9999",Name:" Maria ",Original:pointer(100.0),Discount:pointer(120.0)},{Phone:"5511999999999"},{Phone:"2188888888",Status:pointer("vencida")},{Phone:"12"}}});if err!=nil{t.Fatal(err)};if got.Imported!=2||got.InvoicesUpdated!=1||got.InvoicesCreated!=1{t.Fatalf("got=%+v",got)};if !reflect.DeepEqual(got.Rejected,[]string{"5511999999999","12"}){t.Fatalf("rejected=%v",got.Rejected)};if f.upserted[0].ID!="old"||f.upserted[0].Original!=120||f.upserted[0].Discount!=120{t.Fatalf("invoice=%+v",f.upserted[0])}}

type invoiceFake struct{status string;manual int;inv ManualPaymentInvoice}
func(*invoiceFake)ListInvoices(context.Context,string,int,int)(InvoicePage,error){return InvoicePage{},nil};func(*invoiceFake)UpdateClient(context.Context,string,string,string)error{return nil};func(*invoiceFake)UpdateInvoice(context.Context,string,InvoiceEdit)error{return nil};func(f *invoiceFake)ManualPaymentInvoice(context.Context,string)(ManualPaymentInvoice,bool,error){return f.inv,true,nil};func(f *invoiceFake)InsertManualPayment(context.Context,ManualPaymentInvoice,time.Time)error{f.manual++;return nil};func(f *invoiceFake)SetInvoiceStatus(_ context.Context,_ string,s string)error{f.status=s;return nil};func(*invoiceFake)DeleteAll(context.Context)(DeleteAllResult,error){return DeleteAllResult{},nil}
func TestPaidStatusKeepsManualPaymentSideEffect(t *testing.T){f:=&invoiceFake{inv:ManualPaymentInvoice{ID:"f",ClientID:"c",Original:100,Discount:80}};if err:=NewInvoiceService(f).SetStatus(context.Background(),"f","paga");err!=nil{t.Fatal(err)};if f.status!="paga"||f.manual!=1{t.Fatalf("status=%s manual=%d",f.status,f.manual)}}

type metricFake struct{records []AccessRecord;clients int};func(f metricFake)AccessRecords(context.Context,int)([]AccessRecord,error){return f.records,nil};func(f metricFake)CountClients(context.Context)(int,error){return f.clients,nil};func(f metricFake)ClearAccesses(context.Context)(int,error){return len(f.records),nil}
func TestMetricsUseFirstSuccessfulAccessPerPhone(t *testing.T){loc,_:=time.LoadLocation("America/Sao_Paulo");now:=time.Date(2026,9,1,15,0,0,0,loc);p:="119";old:=time.Date(2026,8,31,12,0,0,0,loc);today:=time.Date(2026,9,1,10,0,0,0,loc);f:=metricFake{clients:99,records:[]AccessRecord{{ID:"new",At:today,AtRaw:today.Format(time.RFC3339),Phone:&p,Success:true,Original:pointer(200.0),Discount:pointer(80.0)},{ID:"old",At:old,AtRaw:old.Format(time.RFC3339),Phone:&p,Success:true,Original:pointer(100.0),Discount:pointer(50.0)}}};s:=NewMetricsService(f);s.now=func()time.Time{return now};m,err:=s.Get(context.Background());if err!=nil{t.Fatal(err)};if m.ClientsTotal!=1||m.ClientsToday!=1||m.ValueViewed!=50||m.DiscountToday!=80||m.DatabaseClients!=99{t.Fatalf("metrics=%+v",m)}}
